### ISSUE TITLE
Something wrong with my config ?

### ISSUE THREAD

**Issue by 3dEADto2** [DaFuqs/EnchantmentGroups#6]
This is my config: `{
  "groups": {
    "melee_luck": [
      "reenchantments:midas_touch",
      "minecraft:looting",
      "eggstractor:eggstracting"
    ],
    "melee_damage": [
      "minecraft:bane_of_arthropods",
      "minecraft:smite",
      "minecraft:sharpness",
      "enchantmentsplus:raider",
      "optional_enchants:nether_bane",
      "enchantmentsplus:endslayer",
      "enchantmentsplus:cubical",
      "incantationem:swine_bane",
      "extra_enchantments:fishermans_blade"
    ],
    "melee_after_kill": [
      "optional_enchants:ninja_style",
      "extra_enchantments:pain_cycle",
      "optional_enchants:angry_lumberjack",
      "extra_enchantments:frenzy",
      "extra_enchantments:lifesteal"
    ],
    "melee_effects": [
      "incantationem:venomous",
      "incantationem:decay",
      "minecraft:fire_aspect",
      "optional_enchants:wither_aspect",
      "enchantmentsplus:levitation",
      "enchantmentsplus:thunderlord",
      "alessandrvenchantments:freezeaspect",
      "optional_enchants:hungering_strike",
      "enchantmentsplus:frostbite"
    ],
    "melee_bonus": [
      "optional_enchants:barbaric",
      "enchantmentsplus:payback",
      "extra_enchantments:enigma_resonator"
    ]
  },
  "treasures": []
}`

The first group works fine but the rest don't. I can for example still combine "enchantmentsplus:raider" & "optional_enchants:nether_bane". Is there something I'm doing wrong?

**Comment by DaFuqs** [comment]
That's an issue that has to be fixed by the corresponding enchantment mods author, I am afraid.
Their code in `canAccept()` (which checks if an enchant is compatible with another) is not calling `super`. 
Please report it to those mods and feel free to link them this issue here. I'm sure the example below will help them out just fine.

Example in the case of [EnchantmentsPlus Raider Enchantment](https://github.com/RobertHoueland/enchantments-plus/blob/fafa7037a1b467d13f27439714da2d2e24a7f7aa/src/main/java/com/robdog777/enchantmentsplus/enchants/RaiderEnchantment.java#L39):

```java
    protected boolean canAccept(Enchantment other) {
        return !(other instanceof DamageEnchantment) && other != EnchantmentsPlus.CUBICAL && other != EnchantmentsPlus.ENDSLAYER;
    }
```

should be 

```java
    protected boolean canAccept(Enchantment other) {
        return super.canAccept(other) && !(other instanceof DamageEnchantment) && other != EnchantmentsPlus.CUBICAL && other != EnchantmentsPlus.ENDSLAYER;
    }
```
